import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {Roboto} from 'next/font/google';
import Script from "next/script";

const roboto_init = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700'],
  variable: '--font-roboto'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script async src="https://www.googletagmanager.com/gtag/js?id=G-C9GB5D8P2P" strategy="afterInteractive"></Script>
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-C9GB5D8P2P');
          `}
        </Script>
      </head>
      <body
        className={`${roboto_init.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
